name: PR to [develop]
on: 
  pull_request:
    branches: [ develop ]

#1. load mise
#2. cache tuist
#3. install tuist
#4. checkout tuist project repository
#5. fetch XCConfig from repository
#6. test tuist project

jobs:
  test:
    runs-on: macos-latest
    env: 
      TUIST_VERSION: 4.12.1
    steps:

      #1. mise툴을 로드
      - uses: jdx/mise-action@v2

      #2. Tuist 캐싱정보 확인
      - name: cache tuist
        id: cache-tuist
        uses: actions/cache@v4
        with:
          path: /Users/runner/.local/share/mise/shims/tuist
          key: ${{ runner.os }}-tuist@${{ env.TUIST_VERSION }}
    
      #3. Tuist 설치, 캐싱 정보확인 실패시 실행
      - name: install tuist
        if: steps.cache-tuist.outputs.cache-hit != 'true'
        run: |
          mise install tuist@${{ env.TUIST_VERSION }}
          mise use -g tuist@${{ env.TUIST_VERSION }}

      - name: check paths
        run: |
          echo "tuist in installed in $(which tuist)"
      
      #4. 프로젝트 다운로드
      - name: checkout project
        uses: actions/checkout@v4
      
      #5. XCConfig파일 및 유출금지파일 다운로드
      - name: fetch Secrets
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.XCCONFIG_REPO }}
          token: ${{ secrets.XCCONFIG_REPO_TOKEN }}
          path: '${{ github.workspace }}/project/Secrets'

      - name: check secret files
        run: |
          echo "Checking configurations are loaded..."
      
      #6. test tuist project
      - name: Test project
        run: |
          cd project
          tuist install
          make test

  


